apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
data:
  grafana.ini: | 
    [datasources]
    name = Prometheus 
    type = prometheus
    access = proxy
    url = http://prometheus:9090